#!/usr/bin/python3

"""
NOTE: Code extracted & modified from the AWS Lambda Container Images for Python 3.9
"""

import sys
sys.path.append('/opt/var/runtime')

from bootstrap import main

if __name__ == '__main__':
    main()
